apiVersion: 1

datasources:
  # PostgreSQL - Base de données safeguard
  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    database: safeguard
    user: postgres
    secureJsonData:
      password: postgres_dev
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
    isDefault: false
    editable: true

  # Prometheus - Métriques des services
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    isDefault: true
    editable: true
