apiVersion: v1
kind: ConfigMap
metadata:
  name: fraud-generator-config
  namespace: fraud-generator
data:
  API_HOST: "0.0.0.0"
  API_PORT: "8010"
  LOG_LEVEL: "INFO"
  LLM_MODEL_NAME: "microsoft/DialoGPT-medium"
  LLM_DEVICE: "cuda"
  LLM_BATCH_SIZE: "1000"
  S3_BUCKET_NAME: "synthetic-fraud"
  KAFKA_TOPIC_SYNTHETIC_TX: "synthetic_tx_events"
  KAFKA_TOPIC_GENERATE_REQUESTS: "synthetic_generate_requests"
