apiVersion: v1
kind: ConfigMap
metadata:
  name: fraudguard-config
  namespace: fraudguard
  labels:
    app.kubernetes.io/name: fraudguard
data:
  LOG_LEVEL: "INFO"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "antifraud"
  REDIS_PORT: "6379"
  KAFKA_ENABLE: "true"
  MODEL_SERVING_URL: "http://model-serving:8001"
  RULES_SERVICE_URL: "http://rules-service:8003"
